### ISSUE TITLE
Allow custom git aliases

### ISSUE THREAD

**Issue by nclsHart** [TheGrowingPlant/mac-playbook#139]
Like zsh aliases, it could be great to allow git aliases customization.

Something like: 

```yaml
git_aliases:
    sl: stash list
    sa: stash apply
    ss: stash save
```
