### ISSUE TITLE
Improve management of custom zsh plugins

### ISSUE THREAD

**Issue by nclsHart** [TheGrowingPlant/mac-playbook#61]
With https://github.com/TheGrowingPlant/mac-playbook/pull/60, we are now adding 3 externals zsh plugins.

For this 3 plugins, we have 2 different modes of operation:
- plugin is installed but need to be activate using config key
- plugin is installed and always activated

I think we could improve this in order to have only one consistent way for handling custom zsh plugins and at the same time, allow user to add their own plugins through configuration.

```yaml
zsh_custom_plugins:
  - name: symfony
    url: git@github.com:TheGrowingPlant/symfony.plugin.zsh.git
  - name: zsh-autosuggestions
    url: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    url: https://github.com/zsh-users/zsh-syntax-highlighting.git
```
Custom plugins should be added at the end of the list and order should be preserved for plugin like zsh-syntax-highlighting which need to be loaded after others.

I identify one problem with this config: we are adding special config to `zshrc` for zsh-syntax-highlighting plugin. Maybe we could handle this using an `extra_config` key or something like this.
